### ISSUE TITLE
In the new versions of XD  this no longer works

### ISSUE THREAD

**Issue by yaronelh** [yoshikinoko/SplitText#2]
It no longer stipulates the text into separate lines, it just combines all of the in the same row

https://i.imgur.com/r5SJPJW.png

**Comment by yoshikinoko** [comment]
@yaronelh thank you for reporting the issue. I had reproduced the problem on XD 25.1.12.7.
I will investigate and submit the fix soon.

**Comment by yaronelh** [comment]
👍

**Comment by yoshikinoko** [comment]
@yaronelh the fix has been released, please update to 1.0.5
